dist: xenial
sudo: false

language: generic

env:
  matrix:
    - K8S_VERSION=v1.15.0
    - K8S_VERSION=v1.14.3
    - K8S_VERSION=v1.13.6
matrix:
  allow_failures:
    - env: K8S_VERSION=v1.13.6

before_script:
  - make setup_tests

script:
  - make test

